Parse option `swap-size`

diff --git a/nixos-fde-config b/nixos-fde-config
--- a/nixos-fde-config
+++ b/nixos-fde-config
@@ -49,6 +49,7 @@ MAIN_DISK=""
 BOOT_KEY=""
 RAW_ROOT_SIZE=""
 ROOT_SIZE=""
+RAW_SWAP_SIZE=""
 SWAP_SIZE=""
 HOME_SIZE=""
 WIPE_DISKS=true
@@ -308,6 +309,27 @@ function warn {
   echo -e "$(yellowbg WARNING:) $1" >&2
 }
 
+######################################################################
+# Ask for confirmation after a warning.
+# Arguments:
+#  Warning message
+# Outputs:
+#   Writes warning to stderr
+# Returns:
+#   0 if action is confirmed, non-zero otherwise
+######################################################################
+function confirmContinue {
+  local message="$1"
+  local reply
+
+  warn "${message}"
+  read -r -p "Would you like to continue? [y/N] " reply
+
+  if [[ "${reply}" != y ]]; then
+    exit 1
+  fi
+}
+
 #### CONVERSION FUNCTIONS
 
 ######################################################################
@@ -328,6 +350,7 @@ function toLongOption {
     '-m') echo '--main-disk' ;;
     '-b') echo '--boot-key' ;;
     '-R') echo '--root-size' ;;
+    '-S') echo '--swap-size' ;;
     *) echo "" ;;
   esac
 }
@@ -621,6 +644,26 @@ function isAtLeast8GiB { isAtLeastNBytes "$(toBytes 8G)" "$1"; }
 ######################################################################
 function isValidSize { [[ "$1" =~ (^[0-9]+$)|(^[0-9]+[kKMGT]$) ]]; }
 
+######################################################################
+# Test if a disk size in bytes is zero or at least 4MiB
+# Arguments:
+#   Size in bytes
+# Returns:
+#   True if the size is zero or 4MiB
+#   False otherwise
+######################################################################
+function isZeroOrAtLeast4MiB { [[ $1 -eq 0 || $1 -ge $(toBytes 4M) ]]; }
+
+######################################################################
+# Test if an integer is not zero
+# Arguments:
+#   Integer value
+# Returns:
+#   True if an integer is not equal to zero
+#   False otherwise
+######################################################################
+function isNotZero { [[ "$1" -ne 0 ]]; }
+
 #### PARSER FUNCTIONS
 
 ######################################################################
@@ -725,6 +768,30 @@ function parseRootSize {
   echo "${size_in_bytes}"
 }
 
+######################################################################
+# Parse swap-size option value.
+# Arguments:
+#   Partition size
+# Returns:
+#   Size in bytes, if the partition size meets minimum requirements
+#   Exit code 1, otherwise
+# Outputs:
+#   Error message if minimum requirements are not met
+######################################################################
+function parseSwapSize {
+  local size="$1"
+  local size_in_bytes
+
+  assert isValidSize "${size}" \
+    error "Specified invalid partition size: ${size}."
+
+  size_in_bytes=$(toBytes "${size}")
+  assert isZeroOrAtLeast4MiB "${size_in_bytes}" \
+    error "Swap size must be either 0 or at least 4MiB."
+
+  echo "${size_in_bytes}"
+}
+
 ################################################################################
 #                        MAIN PROGRAM
 ################################################################################
@@ -744,6 +811,7 @@ for arg in "$@"; do
     '--main-disk') set -- "$@" '-m' ;;
     '--resume') set -- "$@" '-z' ;;
     '--root-size') set -- "$@" '-R' ;;
+    '--swap-size') set -- "$@" '-S' ;;
     '--version') set -- "$@" '-y' ;;
     *) set -- "$@" "$arg" ;;
   esac
@@ -751,7 +819,7 @@ done
 
 # Parse short option value
 OPTIND=1
-while getopts ":hm:b:R:tyz" short_option; do
+while getopts ":hm:b:R:S:tyz" short_option; do
   case "${short_option}" in
     h)
       printHelp
@@ -762,6 +830,10 @@ while getopts ":hm:b:R:tyz" short_option; do
     R)
       ROOT_SIZE="$(run parseRootSize "${short_option}" "${RAW_ROOT_SIZE}")"
       RAW_ROOT_SIZE="${OPTARG}"
+      ;;
+    S)
+      SWAP_SIZE="$(run parseSwapSize "${short_option}" "${RAW_SWAP_SIZE}")"
+      RAW_SWAP_SIZE="${OPTARG}"
       ;;
     t) RUNNING_TEST=1 ;;
     y)
@@ -805,10 +877,18 @@ assert isSet "${BOOT_KEY}" \
   error "the option '-b, --boot-key' is required."
 assert isSet "${ROOT_SIZE}" \
   error "the option '-R, --root-size' is required."
+assert isSet "${SWAP_SIZE}" \
+  error "the option '-S, --swap-size' is required."
 
 # Check that we are NOT Setting up the system and the boot-key on the same disk
 assert isNotMainDisk "${BOOT_KEY}" \
   error "options main-disk and boot-key refer to the same device: ${BOOT_KEY}"
+
+if [[ "${RESUME}" == false ]]; then
+  # Warn about zero-sized partitions and ask for confirmation
+  assert isNotZero "${SWAP_SIZE}" \
+    confirmContinue "no space allocated for SWAP."
+fi
 
 # Stop script execution beyond this point and signal success
 if isRunningUnitTest; then
